name: Build & Upload Model Bundle

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m pytest -q

      - name: Train model bundle
        run: |
          python train_model.py --bundle model_bundle.pkl

      - name: Upload model bundle
        uses: actions/upload-artifact@v4
        with:
          name: model-bundle
          path: model_bundle.pkl
